---
deployment:
  tasks:
    - export DEPLOYPATH=/home/naboishu/public_html/
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R admin $DEPLOYPATH
    - /bin/cp -R destinations $DEPLOYPATH
